package com.serverest.contract.provider;

import au.com.dius.pact.provider.junit5.PactVerificationContext;
import au.com.dius.pact.provider.junit5.PactVerificationInvocationContextProvider;
import au.com.dius.pact.provider.junitsupport.Provider;
import au.com.dius.pact.provider.junitsupport.loader.PactFolder;
import com.serverest.config.Config;
import com.serverest.utils.ServeRestContainer;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.TestTemplate;
import org.junit.jupiter.api.extension.ExtendWith;

@Provider("ServeRestProvider")
@PactFolder("target/pacts") // Reads pacts generated by consumer tests
public class PactProviderTest {

    @BeforeAll
    static void setup() {
        ServeRestContainer.ensureRunning();
        String baseUrl = Config.getBaseUrl();
        System.setProperty("pact.provider.url", baseUrl);
        System.setProperty("pact.verifier.publishResults", "false"); // Don't publish to broker yet
    }

    @TestTemplate
    @ExtendWith(PactVerificationInvocationContextProvider.class)
    void verifyPact(PactVerificationContext context) {
        context.verifyInteraction();
    }
}